modLoader="javafml"
loaderVersion="*"
license="GPL3"
issueTrackerURL="https://github.com/KosmX/emotes/issues"

[[mods]]
modId="emotecraft"
version="${version}"
displayName="Emotecraft"
updateJSONURL = "https://api.modrinth.com/updates/emotecraft/forge_updates.json?neoforge=include"
displayURL="https://kosmx.gitbook.io/emotecraft/"
logoFile="emotecraft_mod_logo.png"
authors="KosmX, dima_dencep"
description="${description}"

[[mixins]]
config = "emotecraft-arch.mixins.json"

[[dependencies.emotecraft]]
modId="playeranimator"
mandatory=true
type="required"
versionRange="[2.0.0,)"
ordering="NONE"
side="BOTH"
