# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: configure gradle
      uses: gradle/wrapper-validation-action@v1
      with:
        java-version: 21

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: 21
    - name: Grant execute permission for gradlew
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x gradlew
    - name: Build All
      uses: gradle/gradle-build-action@v3
      with:
        arguments: buildAll
