# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'microsoft'
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build All
      run: ./gradlew build

    - name: Copy artifacts
      run: |
        mkdir -p artifacts
        cp paper/build/libs/*.jar artifacts/
        cp minecraft/fabric/build/libs/*.jar artifacts/
        cp minecraft/neoforge/build/libs/*.jar artifacts/
    - uses: actions/upload-artifact@v4
      with:
        name: Build Results
        path: artifacts/*.jar
